<?php
/**
 * FrenchNumeriqueProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * FrenchNumeriqueProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;france-identite-numerique&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FrenchNumeriqueProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FrenchNumeriqueProviderOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'given_name' => '\Trinsic\Api\Model\FrenchNumeriqueGivenName',
        'family_name' => 'string',
        'preferred_surname' => 'string',
        'birthdate' => 'string',
        'nationality' => '\Trinsic\Api\Model\FrenchNumeriqueNationality',
        'sex' => 'string',
        'majority' => 'bool',
        'phone_number' => '\Trinsic\Api\Model\FrenchNumeriquePhone',
        'phone_number_verified' => 'bool',
        'email' => 'string',
        'email_verified' => 'bool',
        'birthplace' => 'string',
        'birthplace_label' => 'string',
        'birth_country' => 'string',
        'birth_country_iso' => 'string',
        'birth_country_label' => 'string',
        'birth_department' => 'string',
        'digital_identity_creation_date' => '\DateTime',
        'digital_identity_expiration_date' => '\DateTime',
        'identity_document_type' => 'string',
        'identity_document_number' => 'string',
        'identity_document_emitting_date' => '\DateTime',
        'identity_document_expiration_date' => '\DateTime',
        'identity_document_emitting_country' => 'string',
        'identity_document_mrz' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'given_name' => null,
        'family_name' => null,
        'preferred_surname' => null,
        'birthdate' => null,
        'nationality' => null,
        'sex' => null,
        'majority' => null,
        'phone_number' => null,
        'phone_number_verified' => null,
        'email' => null,
        'email_verified' => null,
        'birthplace' => null,
        'birthplace_label' => null,
        'birth_country' => null,
        'birth_country_iso' => null,
        'birth_country_label' => null,
        'birth_department' => null,
        'digital_identity_creation_date' => 'date',
        'digital_identity_expiration_date' => 'date',
        'identity_document_type' => null,
        'identity_document_number' => null,
        'identity_document_emitting_date' => 'date',
        'identity_document_expiration_date' => 'date',
        'identity_document_emitting_country' => null,
        'identity_document_mrz' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'given_name' => true,
        'family_name' => true,
        'preferred_surname' => true,
        'birthdate' => true,
        'nationality' => true,
        'sex' => true,
        'majority' => true,
        'phone_number' => true,
        'phone_number_verified' => true,
        'email' => true,
        'email_verified' => true,
        'birthplace' => true,
        'birthplace_label' => true,
        'birth_country' => true,
        'birth_country_iso' => true,
        'birth_country_label' => true,
        'birth_department' => true,
        'digital_identity_creation_date' => true,
        'digital_identity_expiration_date' => true,
        'identity_document_type' => true,
        'identity_document_number' => true,
        'identity_document_emitting_date' => true,
        'identity_document_expiration_date' => true,
        'identity_document_emitting_country' => true,
        'identity_document_mrz' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'given_name' => 'givenName',
        'family_name' => 'familyName',
        'preferred_surname' => 'preferredSurname',
        'birthdate' => 'birthdate',
        'nationality' => 'nationality',
        'sex' => 'sex',
        'majority' => 'majority',
        'phone_number' => 'phoneNumber',
        'phone_number_verified' => 'phoneNumberVerified',
        'email' => 'email',
        'email_verified' => 'emailVerified',
        'birthplace' => 'birthplace',
        'birthplace_label' => 'birthplaceLabel',
        'birth_country' => 'birthCountry',
        'birth_country_iso' => 'birthCountryIso',
        'birth_country_label' => 'birthCountryLabel',
        'birth_department' => 'birthDepartment',
        'digital_identity_creation_date' => 'digitalIdentityCreationDate',
        'digital_identity_expiration_date' => 'digitalIdentityExpirationDate',
        'identity_document_type' => 'identityDocumentType',
        'identity_document_number' => 'identityDocumentNumber',
        'identity_document_emitting_date' => 'identityDocumentEmittingDate',
        'identity_document_expiration_date' => 'identityDocumentExpirationDate',
        'identity_document_emitting_country' => 'identityDocumentEmittingCountry',
        'identity_document_mrz' => 'identityDocumentMrz'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'given_name' => 'setGivenName',
        'family_name' => 'setFamilyName',
        'preferred_surname' => 'setPreferredSurname',
        'birthdate' => 'setBirthdate',
        'nationality' => 'setNationality',
        'sex' => 'setSex',
        'majority' => 'setMajority',
        'phone_number' => 'setPhoneNumber',
        'phone_number_verified' => 'setPhoneNumberVerified',
        'email' => 'setEmail',
        'email_verified' => 'setEmailVerified',
        'birthplace' => 'setBirthplace',
        'birthplace_label' => 'setBirthplaceLabel',
        'birth_country' => 'setBirthCountry',
        'birth_country_iso' => 'setBirthCountryIso',
        'birth_country_label' => 'setBirthCountryLabel',
        'birth_department' => 'setBirthDepartment',
        'digital_identity_creation_date' => 'setDigitalIdentityCreationDate',
        'digital_identity_expiration_date' => 'setDigitalIdentityExpirationDate',
        'identity_document_type' => 'setIdentityDocumentType',
        'identity_document_number' => 'setIdentityDocumentNumber',
        'identity_document_emitting_date' => 'setIdentityDocumentEmittingDate',
        'identity_document_expiration_date' => 'setIdentityDocumentExpirationDate',
        'identity_document_emitting_country' => 'setIdentityDocumentEmittingCountry',
        'identity_document_mrz' => 'setIdentityDocumentMrz'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'given_name' => 'getGivenName',
        'family_name' => 'getFamilyName',
        'preferred_surname' => 'getPreferredSurname',
        'birthdate' => 'getBirthdate',
        'nationality' => 'getNationality',
        'sex' => 'getSex',
        'majority' => 'getMajority',
        'phone_number' => 'getPhoneNumber',
        'phone_number_verified' => 'getPhoneNumberVerified',
        'email' => 'getEmail',
        'email_verified' => 'getEmailVerified',
        'birthplace' => 'getBirthplace',
        'birthplace_label' => 'getBirthplaceLabel',
        'birth_country' => 'getBirthCountry',
        'birth_country_iso' => 'getBirthCountryIso',
        'birth_country_label' => 'getBirthCountryLabel',
        'birth_department' => 'getBirthDepartment',
        'digital_identity_creation_date' => 'getDigitalIdentityCreationDate',
        'digital_identity_expiration_date' => 'getDigitalIdentityExpirationDate',
        'identity_document_type' => 'getIdentityDocumentType',
        'identity_document_number' => 'getIdentityDocumentNumber',
        'identity_document_emitting_date' => 'getIdentityDocumentEmittingDate',
        'identity_document_expiration_date' => 'getIdentityDocumentExpirationDate',
        'identity_document_emitting_country' => 'getIdentityDocumentEmittingCountry',
        'identity_document_mrz' => 'getIdentityDocumentMrz'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('given_name', $data ?? [], null);
        $this->setIfExists('family_name', $data ?? [], null);
        $this->setIfExists('preferred_surname', $data ?? [], null);
        $this->setIfExists('birthdate', $data ?? [], null);
        $this->setIfExists('nationality', $data ?? [], null);
        $this->setIfExists('sex', $data ?? [], null);
        $this->setIfExists('majority', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('phone_number_verified', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('email_verified', $data ?? [], null);
        $this->setIfExists('birthplace', $data ?? [], null);
        $this->setIfExists('birthplace_label', $data ?? [], null);
        $this->setIfExists('birth_country', $data ?? [], null);
        $this->setIfExists('birth_country_iso', $data ?? [], null);
        $this->setIfExists('birth_country_label', $data ?? [], null);
        $this->setIfExists('birth_department', $data ?? [], null);
        $this->setIfExists('digital_identity_creation_date', $data ?? [], null);
        $this->setIfExists('digital_identity_expiration_date', $data ?? [], null);
        $this->setIfExists('identity_document_type', $data ?? [], null);
        $this->setIfExists('identity_document_number', $data ?? [], null);
        $this->setIfExists('identity_document_emitting_date', $data ?? [], null);
        $this->setIfExists('identity_document_expiration_date', $data ?? [], null);
        $this->setIfExists('identity_document_emitting_country', $data ?? [], null);
        $this->setIfExists('identity_document_mrz', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets given_name
     *
     * @return \Trinsic\Api\Model\FrenchNumeriqueGivenName|null
     */
    public function getGivenName()
    {
        return $this->container['given_name'];
    }

    /**
     * Sets given_name
     *
     * @param \Trinsic\Api\Model\FrenchNumeriqueGivenName|null $given_name Given name information including the full given name and its structured components (first name and middle name(s)).
     *
     * @return self
     */
    public function setGivenName($given_name)
    {
        if (is_null($given_name)) {
            array_push($this->openAPINullablesSetToNull, 'given_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('given_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['given_name'] = $given_name;

        return $this;
    }

    /**
     * Gets family_name
     *
     * @return string|null
     */
    public function getFamilyName()
    {
        return $this->container['family_name'];
    }

    /**
     * Sets family_name
     *
     * @param string|null $family_name Birth name (nom de naissance) as recorded on the user's French identity document. In France, this is the family name given at birth and may differ from the usage name.
     *
     * @return self
     */
    public function setFamilyName($family_name)
    {
        if (is_null($family_name)) {
            array_push($this->openAPINullablesSetToNull, 'family_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('family_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['family_name'] = $family_name;

        return $this;
    }

    /**
     * Gets preferred_surname
     *
     * @return string|null
     */
    public function getPreferredSurname()
    {
        return $this->container['preferred_surname'];
    }

    /**
     * Sets preferred_surname
     *
     * @param string|null $preferred_surname Usage surname (\"nom d'usage\") - according to French law, this is the surname used in daily life. This is typically a married name or other preferred surname, as opposed to FamilyName which is the birth surname (\"nom de naissance\").
     *
     * @return self
     */
    public function setPreferredSurname($preferred_surname)
    {
        if (is_null($preferred_surname)) {
            array_push($this->openAPINullablesSetToNull, 'preferred_surname');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('preferred_surname', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['preferred_surname'] = $preferred_surname;

        return $this;
    }

    /**
     * Gets birthdate
     *
     * @return string|null
     */
    public function getBirthdate()
    {
        return $this->container['birthdate'];
    }

    /**
     * Sets birthdate
     *
     * @param string|null $birthdate Date of birth in YYYY-MM-DD format, as recorded on the user's French identity document.
     *
     * @return self
     */
    public function setBirthdate($birthdate)
    {
        if (is_null($birthdate)) {
            array_push($this->openAPINullablesSetToNull, 'birthdate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birthdate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birthdate'] = $birthdate;

        return $this;
    }

    /**
     * Gets nationality
     *
     * @return \Trinsic\Api\Model\FrenchNumeriqueNationality|null
     */
    public function getNationality()
    {
        return $this->container['nationality'];
    }

    /**
     * Sets nationality
     *
     * @param \Trinsic\Api\Model\FrenchNumeriqueNationality|null $nationality Nationality information with ISO 3166 alpha-3 code and French label. The label is provided in French (e.g., \"Française\" for French nationality).
     *
     * @return self
     */
    public function setNationality($nationality)
    {
        if (is_null($nationality)) {
            array_push($this->openAPINullablesSetToNull, 'nationality');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nationality', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nationality'] = $nationality;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return string|null
     */
    public function getSex()
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param string|null $sex Sex - \"Male\" or \"Female\".
     *
     * @return self
     */
    public function setSex($sex)
    {
        if (is_null($sex)) {
            array_push($this->openAPINullablesSetToNull, 'sex');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sex', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sex'] = $sex;

        return $this;
    }

    /**
     * Gets majority
     *
     * @return bool|null
     */
    public function getMajority()
    {
        return $this->container['majority'];
    }

    /**
     * Sets majority
     *
     * @param bool|null $majority Majority status (majorité) indicating whether the user has reached the French age of legal majority (18 years old). This value is computed by the provider from the user's birthdate.
     *
     * @return self
     */
    public function setMajority($majority)
    {
        if (is_null($majority)) {
            array_push($this->openAPINullablesSetToNull, 'majority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('majority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['majority'] = $majority;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return \Trinsic\Api\Model\FrenchNumeriquePhone|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param \Trinsic\Api\Model\FrenchNumeriquePhone|null $phone_number Phone number information including the full phone number and its structured components (country prefix and national number).
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            array_push($this->openAPINullablesSetToNull, 'phone_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets phone_number_verified
     *
     * @return bool|null
     */
    public function getPhoneNumberVerified()
    {
        return $this->container['phone_number_verified'];
    }

    /**
     * Sets phone_number_verified
     *
     * @param bool|null $phone_number_verified Whether the phone number has been verified by the provider.
     *
     * @return self
     */
    public function setPhoneNumberVerified($phone_number_verified)
    {
        if (is_null($phone_number_verified)) {
            array_push($this->openAPINullablesSetToNull, 'phone_number_verified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_number_verified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_number_verified'] = $phone_number_verified;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email Email address registered in the user's digital identity account.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets email_verified
     *
     * @return bool|null
     */
    public function getEmailVerified()
    {
        return $this->container['email_verified'];
    }

    /**
     * Sets email_verified
     *
     * @param bool|null $email_verified Whether the email address has been verified by the provider.
     *
     * @return self
     */
    public function setEmailVerified($email_verified)
    {
        if (is_null($email_verified)) {
            array_push($this->openAPINullablesSetToNull, 'email_verified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email_verified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email_verified'] = $email_verified;

        return $this;
    }

    /**
     * Gets birthplace
     *
     * @return string|null
     */
    public function getBirthplace()
    {
        return $this->container['birthplace'];
    }

    /**
     * Sets birthplace
     *
     * @param string|null $birthplace National Institute of Statistics and Economic Studies (INSEE) official geographic code (COG) of the birthplace. This is a 5-digit French administrative code identifying the commune (municipality) of birth. For births in metropolitan France, the first two digits represent the department.              See: https://www.insee.fr/fr/information/2560452
     *
     * @return self
     */
    public function setBirthplace($birthplace)
    {
        if (is_null($birthplace)) {
            array_push($this->openAPINullablesSetToNull, 'birthplace');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birthplace', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birthplace'] = $birthplace;

        return $this;
    }

    /**
     * Gets birthplace_label
     *
     * @return string|null
     */
    public function getBirthplaceLabel()
    {
        return $this->container['birthplace_label'];
    }

    /**
     * Sets birthplace_label
     *
     * @param string|null $birthplace_label Name of the birthplace commune (municipality). If applicable, this includes the full name of the arrondissement (borough).
     *
     * @return self
     */
    public function setBirthplaceLabel($birthplace_label)
    {
        if (is_null($birthplace_label)) {
            array_push($this->openAPINullablesSetToNull, 'birthplace_label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birthplace_label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birthplace_label'] = $birthplace_label;

        return $this;
    }

    /**
     * Gets birth_country
     *
     * @return string|null
     */
    public function getBirthCountry()
    {
        return $this->container['birth_country'];
    }

    /**
     * Sets birth_country
     *
     * @param string|null $birth_country National Institute of Statistics and Economic Studies (INSEE) official geographic code (COG) for the user's country of birth.              LaPoste returns this as a 5-character numeric string. This is a country/territory COG, so it always starts with \"99\" (99xxx). France is coded as 99100.              See full list here: https://www.insee.fr/fr/information/2560452
     *
     * @return self
     */
    public function setBirthCountry($birth_country)
    {
        if (is_null($birth_country)) {
            array_push($this->openAPINullablesSetToNull, 'birth_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_country'] = $birth_country;

        return $this;
    }

    /**
     * Gets birth_country_iso
     *
     * @return string|null
     */
    public function getBirthCountryIso()
    {
        return $this->container['birth_country_iso'];
    }

    /**
     * Sets birth_country_iso
     *
     * @param string|null $birth_country_iso Birth country as an ISO 3166 alpha-3 code.
     *
     * @return self
     */
    public function setBirthCountryIso($birth_country_iso)
    {
        if (is_null($birth_country_iso)) {
            array_push($this->openAPINullablesSetToNull, 'birth_country_iso');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_country_iso', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_country_iso'] = $birth_country_iso;

        return $this;
    }

    /**
     * Gets birth_country_label
     *
     * @return string|null
     */
    public function getBirthCountryLabel()
    {
        return $this->container['birth_country_label'];
    }

    /**
     * Sets birth_country_label
     *
     * @param string|null $birth_country_label Label of the birth country, in English.
     *
     * @return self
     */
    public function setBirthCountryLabel($birth_country_label)
    {
        if (is_null($birth_country_label)) {
            array_push($this->openAPINullablesSetToNull, 'birth_country_label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_country_label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_country_label'] = $birth_country_label;

        return $this;
    }

    /**
     * Gets birth_department
     *
     * @return string|null
     */
    public function getBirthDepartment()
    {
        return $this->container['birth_department'];
    }

    /**
     * Sets birth_department
     *
     * @param string|null $birth_department Number of the department of birth (e.g., \"75\" for Paris, \"2A\" for Corse-du-Sud).              See full list here: https://en.wikipedia.org/wiki/Departments_of_France
     *
     * @return self
     */
    public function setBirthDepartment($birth_department)
    {
        if (is_null($birth_department)) {
            array_push($this->openAPINullablesSetToNull, 'birth_department');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_department', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_department'] = $birth_department;

        return $this;
    }

    /**
     * Gets digital_identity_creation_date
     *
     * @return \DateTime|null
     */
    public function getDigitalIdentityCreationDate()
    {
        return $this->container['digital_identity_creation_date'];
    }

    /**
     * Sets digital_identity_creation_date
     *
     * @param \DateTime|null $digital_identity_creation_date Date when the user's digital identity was created.
     *
     * @return self
     */
    public function setDigitalIdentityCreationDate($digital_identity_creation_date)
    {
        if (is_null($digital_identity_creation_date)) {
            array_push($this->openAPINullablesSetToNull, 'digital_identity_creation_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('digital_identity_creation_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['digital_identity_creation_date'] = $digital_identity_creation_date;

        return $this;
    }

    /**
     * Gets digital_identity_expiration_date
     *
     * @return \DateTime|null
     */
    public function getDigitalIdentityExpirationDate()
    {
        return $this->container['digital_identity_expiration_date'];
    }

    /**
     * Sets digital_identity_expiration_date
     *
     * @param \DateTime|null $digital_identity_expiration_date Date when the digital identity expires. It is valid for 5 years from the date of identity verification. Users are notified ~1 month before and must re-verify identity via the app or in-person at La Poste. After expiration, the identity is deactivated but can be renewed within 1 year; otherwise deleted.
     *
     * @return self
     */
    public function setDigitalIdentityExpirationDate($digital_identity_expiration_date)
    {
        if (is_null($digital_identity_expiration_date)) {
            array_push($this->openAPINullablesSetToNull, 'digital_identity_expiration_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('digital_identity_expiration_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['digital_identity_expiration_date'] = $digital_identity_expiration_date;

        return $this;
    }

    /**
     * Gets identity_document_type
     *
     * @return string|null
     */
    public function getIdentityDocumentType()
    {
        return $this->container['identity_document_type'];
    }

    /**
     * Sets identity_document_type
     *
     * @param string|null $identity_document_type Type of identity document used for verification. Can be \"ID_CARD\", \"PASSPORT\", or \"RESIDENCE_PERMIT\".
     *
     * @return self
     */
    public function setIdentityDocumentType($identity_document_type)
    {
        if (is_null($identity_document_type)) {
            array_push($this->openAPINullablesSetToNull, 'identity_document_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identity_document_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identity_document_type'] = $identity_document_type;

        return $this;
    }

    /**
     * Gets identity_document_number
     *
     * @return string|null
     */
    public function getIdentityDocumentNumber()
    {
        return $this->container['identity_document_number'];
    }

    /**
     * Sets identity_document_number
     *
     * @param string|null $identity_document_number Identity document number as it appears on the ID Card, Passport or Residence Permit.
     *
     * @return self
     */
    public function setIdentityDocumentNumber($identity_document_number)
    {
        if (is_null($identity_document_number)) {
            array_push($this->openAPINullablesSetToNull, 'identity_document_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identity_document_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identity_document_number'] = $identity_document_number;

        return $this;
    }

    /**
     * Gets identity_document_emitting_date
     *
     * @return \DateTime|null
     */
    public function getIdentityDocumentEmittingDate()
    {
        return $this->container['identity_document_emitting_date'];
    }

    /**
     * Sets identity_document_emitting_date
     *
     * @param \DateTime|null $identity_document_emitting_date Date when the identity document was issued.
     *
     * @return self
     */
    public function setIdentityDocumentEmittingDate($identity_document_emitting_date)
    {
        if (is_null($identity_document_emitting_date)) {
            array_push($this->openAPINullablesSetToNull, 'identity_document_emitting_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identity_document_emitting_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identity_document_emitting_date'] = $identity_document_emitting_date;

        return $this;
    }

    /**
     * Gets identity_document_expiration_date
     *
     * @return \DateTime|null
     */
    public function getIdentityDocumentExpirationDate()
    {
        return $this->container['identity_document_expiration_date'];
    }

    /**
     * Sets identity_document_expiration_date
     *
     * @param \DateTime|null $identity_document_expiration_date Date when the identity document expires.
     *
     * @return self
     */
    public function setIdentityDocumentExpirationDate($identity_document_expiration_date)
    {
        if (is_null($identity_document_expiration_date)) {
            array_push($this->openAPINullablesSetToNull, 'identity_document_expiration_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identity_document_expiration_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identity_document_expiration_date'] = $identity_document_expiration_date;

        return $this;
    }

    /**
     * Gets identity_document_emitting_country
     *
     * @return string|null
     */
    public function getIdentityDocumentEmittingCountry()
    {
        return $this->container['identity_document_emitting_country'];
    }

    /**
     * Sets identity_document_emitting_country
     *
     * @param string|null $identity_document_emitting_country Country that issued the identity document (ISO 3166 alpha-3 code).
     *
     * @return self
     */
    public function setIdentityDocumentEmittingCountry($identity_document_emitting_country)
    {
        if (is_null($identity_document_emitting_country)) {
            array_push($this->openAPINullablesSetToNull, 'identity_document_emitting_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identity_document_emitting_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identity_document_emitting_country'] = $identity_document_emitting_country;

        return $this;
    }

    /**
     * Gets identity_document_mrz
     *
     * @return string|null
     */
    public function getIdentityDocumentMrz()
    {
        return $this->container['identity_document_mrz'];
    }

    /**
     * Sets identity_document_mrz
     *
     * @param string|null $identity_document_mrz Machine Readable Zone (MRZ) data from the ID Card, Passport or Residence Permit.
     *
     * @return self
     */
    public function setIdentityDocumentMrz($identity_document_mrz)
    {
        if (is_null($identity_document_mrz)) {
            array_push($this->openAPINullablesSetToNull, 'identity_document_mrz');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identity_document_mrz', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identity_document_mrz'] = $identity_document_mrz;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


