<?php
/**
 * SignzyIndiaAadhaarFetchProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * SignzyIndiaAadhaarFetchProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;india-digilocker-aadhaar-fetch&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SignzyIndiaAadhaarFetchProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SignzyIndiaAadhaarFetchProviderOutput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'document_type' => 'string',
        'timestamp' => '\DateTime',
        'time_to_live' => '\DateTime',
        'aadhaar_number_last_four' => 'string',
        'claims' => '\Trinsic\Api\Model\AadhaarClaims',
        'localized_claims' => '\Trinsic\Api\Model\AadhaarLocalizedClaims',
        'document_signature_validated' => 'bool',
        'digilocker_id' => 'string',
        'issuer_id' => 'string',
        'issuer' => 'string',
        'mobile_phone' => 'string',
        'scope' => 'string[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'document_type' => null,
        'timestamp' => 'date-time',
        'time_to_live' => 'date-time',
        'aadhaar_number_last_four' => null,
        'claims' => null,
        'localized_claims' => null,
        'document_signature_validated' => null,
        'digilocker_id' => null,
        'issuer_id' => null,
        'issuer' => null,
        'mobile_phone' => null,
        'scope' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'document_type' => true,
        'timestamp' => true,
        'time_to_live' => true,
        'aadhaar_number_last_four' => true,
        'claims' => true,
        'localized_claims' => true,
        'document_signature_validated' => false,
        'digilocker_id' => true,
        'issuer_id' => true,
        'issuer' => true,
        'mobile_phone' => true,
        'scope' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'document_type' => 'documentType',
        'timestamp' => 'timestamp',
        'time_to_live' => 'timeToLive',
        'aadhaar_number_last_four' => 'aadhaarNumberLastFour',
        'claims' => 'claims',
        'localized_claims' => 'localizedClaims',
        'document_signature_validated' => 'documentSignatureValidated',
        'digilocker_id' => 'digilockerId',
        'issuer_id' => 'issuerId',
        'issuer' => 'issuer',
        'mobile_phone' => 'mobilePhone',
        'scope' => 'scope'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'document_type' => 'setDocumentType',
        'timestamp' => 'setTimestamp',
        'time_to_live' => 'setTimeToLive',
        'aadhaar_number_last_four' => 'setAadhaarNumberLastFour',
        'claims' => 'setClaims',
        'localized_claims' => 'setLocalizedClaims',
        'document_signature_validated' => 'setDocumentSignatureValidated',
        'digilocker_id' => 'setDigilockerId',
        'issuer_id' => 'setIssuerId',
        'issuer' => 'setIssuer',
        'mobile_phone' => 'setMobilePhone',
        'scope' => 'setScope'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'document_type' => 'getDocumentType',
        'timestamp' => 'getTimestamp',
        'time_to_live' => 'getTimeToLive',
        'aadhaar_number_last_four' => 'getAadhaarNumberLastFour',
        'claims' => 'getClaims',
        'localized_claims' => 'getLocalizedClaims',
        'document_signature_validated' => 'getDocumentSignatureValidated',
        'digilocker_id' => 'getDigilockerId',
        'issuer_id' => 'getIssuerId',
        'issuer' => 'getIssuer',
        'mobile_phone' => 'getMobilePhone',
        'scope' => 'getScope'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('document_type', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('time_to_live', $data ?? [], null);
        $this->setIfExists('aadhaar_number_last_four', $data ?? [], null);
        $this->setIfExists('claims', $data ?? [], null);
        $this->setIfExists('localized_claims', $data ?? [], null);
        $this->setIfExists('document_signature_validated', $data ?? [], null);
        $this->setIfExists('digilocker_id', $data ?? [], null);
        $this->setIfExists('issuer_id', $data ?? [], null);
        $this->setIfExists('issuer', $data ?? [], null);
        $this->setIfExists('mobile_phone', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['document_signature_validated'] === null) {
            $invalidProperties[] = "'document_signature_validated' can't be null";
        }
        if ($this->container['scope'] === null) {
            $invalidProperties[] = "'scope' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets document_type
     *
     * @return string|null
     */
    public function getDocumentType()
    {
        return $this->container['document_type'];
    }

    /**
     * Sets document_type
     *
     * @param string|null $document_type The document type from which the identity data was retrieved.
     *
     * @return self
     */
    public function setDocumentType($document_type)
    {
        if (is_null($document_type)) {
            array_push($this->openAPINullablesSetToNull, 'document_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_type'] = $document_type;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp The timestamp when the signed document was generated and verified.
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            array_push($this->openAPINullablesSetToNull, 'timestamp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('timestamp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets time_to_live
     *
     * @return \DateTime|null
     */
    public function getTimeToLive()
    {
        return $this->container['time_to_live'];
    }

    /**
     * Sets time_to_live
     *
     * @param \DateTime|null $time_to_live The validity expiration timestamp for the verification document.
     *
     * @return self
     */
    public function setTimeToLive($time_to_live)
    {
        if (is_null($time_to_live)) {
            array_push($this->openAPINullablesSetToNull, 'time_to_live');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_to_live', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_to_live'] = $time_to_live;

        return $this;
    }

    /**
     * Gets aadhaar_number_last_four
     *
     * @return string|null
     */
    public function getAadhaarNumberLastFour()
    {
        return $this->container['aadhaar_number_last_four'];
    }

    /**
     * Sets aadhaar_number_last_four
     *
     * @param string|null $aadhaar_number_last_four The Aadhaar number (UID) value for the individual.              This is only the last four digits of the Aadhaar number.
     *
     * @return self
     */
    public function setAadhaarNumberLastFour($aadhaar_number_last_four)
    {
        if (is_null($aadhaar_number_last_four)) {
            array_push($this->openAPINullablesSetToNull, 'aadhaar_number_last_four');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('aadhaar_number_last_four', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['aadhaar_number_last_four'] = $aadhaar_number_last_four;

        return $this;
    }

    /**
     * Gets claims
     *
     * @return \Trinsic\Api\Model\AadhaarClaims|null
     */
    public function getClaims()
    {
        return $this->container['claims'];
    }

    /**
     * Sets claims
     *
     * @param \Trinsic\Api\Model\AadhaarClaims|null $claims The claims extracted from the Aadhaar document.
     *
     * @return self
     */
    public function setClaims($claims)
    {
        if (is_null($claims)) {
            array_push($this->openAPINullablesSetToNull, 'claims');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('claims', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['claims'] = $claims;

        return $this;
    }

    /**
     * Gets localized_claims
     *
     * @return \Trinsic\Api\Model\AadhaarLocalizedClaims|null
     */
    public function getLocalizedClaims()
    {
        return $this->container['localized_claims'];
    }

    /**
     * Sets localized_claims
     *
     * @param \Trinsic\Api\Model\AadhaarLocalizedClaims|null $localized_claims The localized claims extracted from the Aadhaar document.
     *
     * @return self
     */
    public function setLocalizedClaims($localized_claims)
    {
        if (is_null($localized_claims)) {
            array_push($this->openAPINullablesSetToNull, 'localized_claims');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('localized_claims', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['localized_claims'] = $localized_claims;

        return $this;
    }

    /**
     * Gets document_signature_validated
     *
     * @return bool
     */
    public function getDocumentSignatureValidated()
    {
        return $this->container['document_signature_validated'];
    }

    /**
     * Sets document_signature_validated
     *
     * @param bool $document_signature_validated Whether our own validation of the Aadhaar document signature and certificate chain succeeded.              When the signed document (e.g. Digilocker XML) is available, we validate it using the standard CCA/SafeScrypt chain. When the document is not returned, the signature cannot be validated and this is false. Some providers (e.g. Signzy) also supply a separate DSC validation indicator in the webhook payload; that is independent of this flag, which reflects only our validation.
     *
     * @return self
     */
    public function setDocumentSignatureValidated($document_signature_validated)
    {
        if (is_null($document_signature_validated)) {
            throw new \InvalidArgumentException('non-nullable document_signature_validated cannot be null');
        }
        $this->container['document_signature_validated'] = $document_signature_validated;

        return $this;
    }

    /**
     * Gets digilocker_id
     *
     * @return string|null
     */
    public function getDigilockerId()
    {
        return $this->container['digilocker_id'];
    }

    /**
     * Sets digilocker_id
     *
     * @param string|null $digilocker_id DigiLocker's 36-character stable account identifier.              This identifier is deemed safe to use to reference the individual. *Note, the format is not guaranteed to be a UUID.
     *
     * @return self
     */
    public function setDigilockerId($digilocker_id)
    {
        if (is_null($digilocker_id)) {
            array_push($this->openAPINullablesSetToNull, 'digilocker_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('digilocker_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['digilocker_id'] = $digilocker_id;

        return $this;
    }

    /**
     * Gets issuer_id
     *
     * @return string|null
     */
    public function getIssuerId()
    {
        return $this->container['issuer_id'];
    }

    /**
     * Sets issuer_id
     *
     * @param string|null $issuer_id The identifier for the issuer of the DigiLocker document.
     *
     * @return self
     */
    public function setIssuerId($issuer_id)
    {
        if (is_null($issuer_id)) {
            array_push($this->openAPINullablesSetToNull, 'issuer_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuer_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuer_id'] = $issuer_id;

        return $this;
    }

    /**
     * Gets issuer
     *
     * @return string|null
     */
    public function getIssuer()
    {
        return $this->container['issuer'];
    }

    /**
     * Sets issuer
     *
     * @param string|null $issuer Issuer name for the DigiLocker document.
     *
     * @return self
     */
    public function setIssuer($issuer)
    {
        if (is_null($issuer)) {
            array_push($this->openAPINullablesSetToNull, 'issuer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuer', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuer'] = $issuer;

        return $this;
    }

    /**
     * Gets mobile_phone
     *
     * @return string|null
     */
    public function getMobilePhone()
    {
        return $this->container['mobile_phone'];
    }

    /**
     * Sets mobile_phone
     *
     * @param string|null $mobile_phone The individual's mobile phone number from DigiLocker's account details.
     *
     * @return self
     */
    public function setMobilePhone($mobile_phone)
    {
        if (is_null($mobile_phone)) {
            array_push($this->openAPINullablesSetToNull, 'mobile_phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mobile_phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mobile_phone'] = $mobile_phone;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string[]
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string[] $scope DigiLocker consent scopes that the individual actually consented to for this session. Included in provider output so customers can verify what was granted: the customer does not control these—the individual chooses scopes in the DigiLocker consent UI, and there is no way to pre-select or enforce them. This is a common source of error (e.g. the individual skips a scope), so surfacing the granted scopes lets customers confirm the session had the expected consent.
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }
        $this->container['scope'] = $scope;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


