<?php
/**
 * SwedenBankIdProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * SwedenBankIdProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;sweden-bankid&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SwedenBankIdProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SwedenBankIdProviderOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'full_name' => 'string',
        'date_of_birth' => '\DateTime',
        'personal_identity_number' => 'string',
        'given_name' => 'string',
        'family_name' => 'string',
        'country' => 'string',
        'certificate_policy' => 'string',
        'common_name' => 'string',
        'distinguished_name' => 'string',
        'personal_identity_number_issuing_country' => 'string',
        'authentication_device_ip' => 'string',
        'not_before' => '\DateTime',
        'not_after' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'full_name' => null,
        'date_of_birth' => 'date',
        'personal_identity_number' => null,
        'given_name' => null,
        'family_name' => null,
        'country' => null,
        'certificate_policy' => null,
        'common_name' => null,
        'distinguished_name' => null,
        'personal_identity_number_issuing_country' => null,
        'authentication_device_ip' => null,
        'not_before' => 'date-time',
        'not_after' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'full_name' => true,
        'date_of_birth' => true,
        'personal_identity_number' => true,
        'given_name' => true,
        'family_name' => true,
        'country' => true,
        'certificate_policy' => true,
        'common_name' => true,
        'distinguished_name' => true,
        'personal_identity_number_issuing_country' => true,
        'authentication_device_ip' => true,
        'not_before' => true,
        'not_after' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'full_name' => 'fullName',
        'date_of_birth' => 'dateOfBirth',
        'personal_identity_number' => 'personalIdentityNumber',
        'given_name' => 'givenName',
        'family_name' => 'familyName',
        'country' => 'country',
        'certificate_policy' => 'certificatePolicy',
        'common_name' => 'commonName',
        'distinguished_name' => 'distinguishedName',
        'personal_identity_number_issuing_country' => 'personalIdentityNumberIssuingCountry',
        'authentication_device_ip' => 'authenticationDeviceIp',
        'not_before' => 'notBefore',
        'not_after' => 'notAfter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'full_name' => 'setFullName',
        'date_of_birth' => 'setDateOfBirth',
        'personal_identity_number' => 'setPersonalIdentityNumber',
        'given_name' => 'setGivenName',
        'family_name' => 'setFamilyName',
        'country' => 'setCountry',
        'certificate_policy' => 'setCertificatePolicy',
        'common_name' => 'setCommonName',
        'distinguished_name' => 'setDistinguishedName',
        'personal_identity_number_issuing_country' => 'setPersonalIdentityNumberIssuingCountry',
        'authentication_device_ip' => 'setAuthenticationDeviceIp',
        'not_before' => 'setNotBefore',
        'not_after' => 'setNotAfter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'full_name' => 'getFullName',
        'date_of_birth' => 'getDateOfBirth',
        'personal_identity_number' => 'getPersonalIdentityNumber',
        'given_name' => 'getGivenName',
        'family_name' => 'getFamilyName',
        'country' => 'getCountry',
        'certificate_policy' => 'getCertificatePolicy',
        'common_name' => 'getCommonName',
        'distinguished_name' => 'getDistinguishedName',
        'personal_identity_number_issuing_country' => 'getPersonalIdentityNumberIssuingCountry',
        'authentication_device_ip' => 'getAuthenticationDeviceIp',
        'not_before' => 'getNotBefore',
        'not_after' => 'getNotAfter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('full_name', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('personal_identity_number', $data ?? [], null);
        $this->setIfExists('given_name', $data ?? [], null);
        $this->setIfExists('family_name', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('certificate_policy', $data ?? [], null);
        $this->setIfExists('common_name', $data ?? [], null);
        $this->setIfExists('distinguished_name', $data ?? [], null);
        $this->setIfExists('personal_identity_number_issuing_country', $data ?? [], null);
        $this->setIfExists('authentication_device_ip', $data ?? [], null);
        $this->setIfExists('not_before', $data ?? [], null);
        $this->setIfExists('not_after', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets full_name
     *
     * @return string|null
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param string|null $full_name The full name of the individual.
     *
     * @return self
     */
    public function setFullName($full_name)
    {
        if (is_null($full_name)) {
            array_push($this->openAPINullablesSetToNull, 'full_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('full_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return \DateTime|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param \DateTime|null $date_of_birth The date of birth of the individual.
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_birth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_birth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets personal_identity_number
     *
     * @return string|null
     */
    public function getPersonalIdentityNumber()
    {
        return $this->container['personal_identity_number'];
    }

    /**
     * Sets personal_identity_number
     *
     * @param string|null $personal_identity_number The Swedish personal number (personnummer) associated with the verified individual. The value is typically a 12-digit number. This is in the format YYYYMMDDXXXX, where: - YYYYMMDD is the date of birth. - XXXX is an individual number, indicating gender.              If XXXX is even, the individual is female. If XXXX is odd, the individual is male.
     *
     * @return self
     */
    public function setPersonalIdentityNumber($personal_identity_number)
    {
        if (is_null($personal_identity_number)) {
            array_push($this->openAPINullablesSetToNull, 'personal_identity_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personal_identity_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['personal_identity_number'] = $personal_identity_number;

        return $this;
    }

    /**
     * Gets given_name
     *
     * @return string|null
     */
    public function getGivenName()
    {
        return $this->container['given_name'];
    }

    /**
     * Sets given_name
     *
     * @param string|null $given_name The given name of the individual
     *
     * @return self
     */
    public function setGivenName($given_name)
    {
        if (is_null($given_name)) {
            array_push($this->openAPINullablesSetToNull, 'given_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('given_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['given_name'] = $given_name;

        return $this;
    }

    /**
     * Gets family_name
     *
     * @return string|null
     */
    public function getFamilyName()
    {
        return $this->container['family_name'];
    }

    /**
     * Sets family_name
     *
     * @param string|null $family_name The family name of the individual
     *
     * @return self
     */
    public function setFamilyName($family_name)
    {
        if (is_null($family_name)) {
            array_push($this->openAPINullablesSetToNull, 'family_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('family_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['family_name'] = $family_name;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country The end user's country on the verified certificate. This is ISO 2-character code of the country.
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            array_push($this->openAPINullablesSetToNull, 'country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets certificate_policy
     *
     * @return string|null
     */
    public function getCertificatePolicy()
    {
        return $this->container['certificate_policy'];
    }

    /**
     * Sets certificate_policy
     *
     * @param string|null $certificate_policy The object identifier policy of the individual's verified certificate
     *
     * @return self
     */
    public function setCertificatePolicy($certificate_policy)
    {
        if (is_null($certificate_policy)) {
            array_push($this->openAPINullablesSetToNull, 'certificate_policy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('certificate_policy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['certificate_policy'] = $certificate_policy;

        return $this;
    }

    /**
     * Gets common_name
     *
     * @return string|null
     */
    public function getCommonName()
    {
        return $this->container['common_name'];
    }

    /**
     * Sets common_name
     *
     * @param string|null $common_name The common name of the end user's verified certificate
     *
     * @return self
     */
    public function setCommonName($common_name)
    {
        if (is_null($common_name)) {
            array_push($this->openAPINullablesSetToNull, 'common_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('common_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['common_name'] = $common_name;

        return $this;
    }

    /**
     * Gets distinguished_name
     *
     * @return string|null
     */
    public function getDistinguishedName()
    {
        return $this->container['distinguished_name'];
    }

    /**
     * Sets distinguished_name
     *
     * @param string|null $distinguished_name The distinguished name of the end user's verified certificate
     *
     * @return self
     */
    public function setDistinguishedName($distinguished_name)
    {
        if (is_null($distinguished_name)) {
            array_push($this->openAPINullablesSetToNull, 'distinguished_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('distinguished_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['distinguished_name'] = $distinguished_name;

        return $this;
    }

    /**
     * Gets personal_identity_number_issuing_country
     *
     * @return string|null
     */
    public function getPersonalIdentityNumberIssuingCountry()
    {
        return $this->container['personal_identity_number_issuing_country'];
    }

    /**
     * Sets personal_identity_number_issuing_country
     *
     * @param string|null $personal_identity_number_issuing_country The country that issued the Swedish personal number. This is an ISO 2-character code of the country and is extracted from the certificate. This will always be `SE`.
     *
     * @return self
     */
    public function setPersonalIdentityNumberIssuingCountry($personal_identity_number_issuing_country)
    {
        if (is_null($personal_identity_number_issuing_country)) {
            array_push($this->openAPINullablesSetToNull, 'personal_identity_number_issuing_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('personal_identity_number_issuing_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['personal_identity_number_issuing_country'] = $personal_identity_number_issuing_country;

        return $this;
    }

    /**
     * Gets authentication_device_ip
     *
     * @return string|null
     */
    public function getAuthenticationDeviceIp()
    {
        return $this->container['authentication_device_ip'];
    }

    /**
     * Sets authentication_device_ip
     *
     * @param string|null $authentication_device_ip The IP address of the device used for authentication
     *
     * @return self
     */
    public function setAuthenticationDeviceIp($authentication_device_ip)
    {
        if (is_null($authentication_device_ip)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_device_ip');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_device_ip', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_device_ip'] = $authentication_device_ip;

        return $this;
    }

    /**
     * Gets not_before
     *
     * @return \DateTime|null
     */
    public function getNotBefore()
    {
        return $this->container['not_before'];
    }

    /**
     * Sets not_before
     *
     * @param \DateTime|null $not_before The certificate validity start date (not before) in UTC
     *
     * @return self
     */
    public function setNotBefore($not_before)
    {
        if (is_null($not_before)) {
            array_push($this->openAPINullablesSetToNull, 'not_before');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('not_before', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['not_before'] = $not_before;

        return $this;
    }

    /**
     * Gets not_after
     *
     * @return \DateTime|null
     */
    public function getNotAfter()
    {
        return $this->container['not_after'];
    }

    /**
     * Sets not_after
     *
     * @param \DateTime|null $not_after The certificate validity end date (not after) in UTC
     *
     * @return self
     */
    public function setNotAfter($not_after)
    {
        if (is_null($not_after)) {
            array_push($this->openAPINullablesSetToNull, 'not_after');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('not_after', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['not_after'] = $not_after;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


