<?php
/**
 * CreateAdvancedProviderSessionResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Trinsic\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateAdvancedProviderSessionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CreateAdvancedProviderSessionResponse
 * @package     Trinsic\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateAdvancedProviderSessionResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateAdvancedProviderSessionResponse"
     */
    public function testCreateAdvancedProviderSessionResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "result_collection"
     */
    public function testPropertyResultCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "next_step"
     */
    public function testPropertyNextStep()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
