<?php
/**
 * SwedenBankIdProviderOutputTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Trinsic\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SwedenBankIdProviderOutputTest Class Doc Comment
 *
 * @category    Class
 * @description Exposed properties for the &#x60;sweden-bankid&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package     Trinsic\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SwedenBankIdProviderOutputTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SwedenBankIdProviderOutput"
     */
    public function testSwedenBankIdProviderOutput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "full_name"
     */
    public function testPropertyFullName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "personal_identity_number"
     */
    public function testPropertyPersonalIdentityNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "given_name"
     */
    public function testPropertyGivenName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "family_name"
     */
    public function testPropertyFamilyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "certificate_policy"
     */
    public function testPropertyCertificatePolicy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "common_name"
     */
    public function testPropertyCommonName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "distinguished_name"
     */
    public function testPropertyDistinguishedName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "personal_identity_number_issuing_country"
     */
    public function testPropertyPersonalIdentityNumberIssuingCountry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authentication_device_ip"
     */
    public function testPropertyAuthenticationDeviceIp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "not_before"
     */
    public function testPropertyNotBefore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "not_after"
     */
    public function testPropertyNotAfter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
